### ISSUE TITLE
[Feature]: Support for generating GO code

### ISSUE THREAD

**Issue by anuragagarwal561994** [ascopes/protobuf-maven-plugin#515]
### Brief description

Currently the language plugin is missing code-generation for go language

### Aims and goals

It would be greate to have this feature as a lot of projects use go and proto together

### Would you like to contribute to this feature?

- [ ] Yes, I'd like to contribute this change!

**Comment by ascopes** [comment]
Does protoc-gen-go being included as a binary path plugin achieve what is needed for this, or is there further requirements around building Go sources from a Maven project?

**Comment by anuragagarwal561994** [comment]
I haven't tried this part though, I will try it once I just thought like we have done for other languages it would make sense to do it for go as well.

If not this, can an example be included?

**Comment by ascopes** [comment]
If you have protoc-gen-go available on your $PATH, you can reference it via https://ascopes.github.io/protobuf-maven-plugin/using-protoc-plugins.html (the "binary plugins from system path part")

Right now, if you wish to download and execute the plugin as part of the Maven command, I don't think it will work outside Windows since Google provide this as a tar.gz which doesn't have a FileSystem provider in the JRE. A workaround would be to download the binary and extract it to a known location before invoking the plugin, and then using the "binary plugins from specific locations" docs on the link above.

I think to be able to support downloading and running though we'd need a whole tar file system... I had a quick browse online and some stuff vaguely resembling what we need would be available but it would likely still be a fairly significant piece of work, so if the other ways of doing this work well enough for the time being that'd be the recommended approach for now.

**Comment by anuragagarwal561994** [comment]
I tried the above and it works, sample

```xml
<execution>
    <id>go</id>
    <phase>generate-sources</phase>
    <goals>
        <goal>generate</goal>
    </goals>
    <configuration>
        <javaEnabled>false</javaEnabled>
        <binaryPathPlugins>
            <binaryPathPlugin>
                <name>protoc-gen-go</name>
            </binaryPathPlugin>
            <binaryPathPlugin>
                <name>protoc-gen-go-grpc</name>
            </binaryPathPlugin>
        </binaryPathPlugins>
        <outputDirectory>${project.basedir}/go</outputDirectory>
    </configuration>
</execution>
```

I have used aqua.yaml

```yaml
checksum:
  enabled: true
  require_checksum: true
  supported_envs:
  - all
registries:
- type: standard
  ref: v4.231.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: grpc/grpc-go/protoc-gen-go-grpc@cmd/protoc-gen-go-grpc/v1.3.0
- name: protocolbuffers/protobuf-go/protoc-gen-go@v1.31.0
- name: golang/go@go1.20.2
```

To have these respectively in my PATH

Referencing this here for others to have an example for usages, may be if possible can be included as an example or we can close this issue. @ascopes
